# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TZHighlight
                                 A QGIS plugin
 Highlights UTC timezone by selected object
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-15
        copyright            : (C) 2022 by Irina Ogorodova
        email                : ogorodova@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TZHighlight class from file TZHighlight.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tz_highlight import TZHighlight
    return TZHighlight(iface)
